axis_order:
- p
- g
- c
channels:
- config: gfp
  exposure: 10.0
  group: Filter cubes
- config: rfp
  exposure: 10.0
  group: Filter cubes
grid_plan:
  bottom: 0.0
  fov_height: 13312.0
  fov_width: 13312.0
  left: 0.0
  overlap:
  - 5.0
  - 5.0
  right: 0.0
  top: 0.0
metadata:
  napari_micromanager:
    split_channels: false
  pymmcore_widgets:
    format: ome-zarr
    save_dir: D:\fishpicker_expts
    save_name: ''
    should_save: true
    version: 0.9.1
stage_positions:
- x: -34421.6
  y: -10729.800000000001
  z: 8540.01
